# per 100 gm
INGREDIENTS = {'bengal gram': {'carbs': '59.8',
                 'fats': '5.6',
                 'fiber': '15.3',
                 'protein': '20.8'},
 'besan': {'carbs': '57.8', 'fats': '6.6', 'fiber': '10.8', 'protein': '22.3'},
 'black gram': {'carbs': '59.6',
                'fats': '1.4',
                'fiber': '11.7',
                'protein': '24.0'},
 'butter': {'carbs': '0.0', 'fats': '81.0', 'fiber': '0.0', 'protein': '0.0'},
 'cashewnut': {'carbs': '22.3',
               'fats': '46.9',
               'fiber': '3.3',
               'protein': '21.2'},
 'chillies dry': {'carbs': '31.6',
                  'fats': '6.2',
                  'fiber': '0.0',
                  'protein': '15.9'},
 'coconut dry': {'carbs': '18.4',
                 'fats': '62.3',
                 'fiber': '16.3',
                 'protein': '6.8'},
 'coconut oil': {'carbs': '0.0',
                 'fats': '100.0',
                 'fiber': '0.0',
                 'protein': '0.0'},
 'coriander leaves': {'carbs': '6.3',
                      'fats': '0.6',
                      'fiber': '4.3',
                      'protein': '3.3'},
 'cumin seeds': {'carbs': '36.6',
                 'fats': '15.0',
                 'fiber': '30.0',
                 'protein': '18.7'},
 'curds': {'carbs': '3.0', 'fats': '4.0', 'fiber': '0.0', 'protein': '3.1'},
 'curry leaves': {'carbs': '18.7',
                  'fats': '1.0',
                  'fiber': '16.3',
                  'protein': '6.1'},
 'gingelly oil': {'carbs': '0.0',
                  'fats': '100.0',
                  'fiber': '0.0',
                  'protein': '0.0'},
 'ginger fresh': {'carbs': '12.3',
                  'fats': '0.9',
                  'fiber': '6.0',
                  'protein': '2.3'},
 'green chillies': {'carbs': '3.0',
                    'fats': '0.6',
                    'fiber': '1.5',
                    'protein': '2.9'},
 'groundnut oil': {'carbs': '0.0',
                   'fats': '100.0',
                   'fiber': '0.0',
                   'protein': '0.0'},
 'milk': {'carbs': '4.4', 'fats': '4.1', 'fiber': '0.0', 'protein': '3.2'},
 'mint': {'carbs': '5.8', 'fats': '0.6', 'fiber': '6.3', 'protein': '4.8'},
 'mustard oil': {'carbs': '0.0',
                 'fats': '100.0',
                 'fiber': '0.0',
                 'protein': '0.0'},
 'mustard seeds': {'carbs': '23.8',
                   'fats': '39.7',
                   'fiber': '13.6',
                   'protein': '20.0'},
 'onion big': {'carbs': '11.1',
               'fats': '0.1',
               'fiber': '2.5',
               'protein': '1.2'},
 'palmolein oil': {'carbs': '0.0',
                   'fats': '100.0',
                   'fiber': '0.0',
                   'protein': '0.0'},
 'paneer': {'carbs': '1.2', 'fats': '20.8', 'fiber': '0.0', 'protein': '18.3'},
 'potato': {'carbs': '22.6', 'fats': '0.1', 'fiber': '1.7', 'protein': '1.6'},
 'rice parboiled handpounded': {'carbs': '77.4',
                                'fats': '0.6',
                                'fiber': '1.8',
                                'protein': '8.5'},
 'rice raw handpounded': {'carbs': '76.7',
                          'fats': '1.0',
                          'fiber': '1.3',
                          'protein': '7.5'},
 'salt': {'carbs': '0.0', 'fats': '0.0', 'fiber': '0.0', 'protein': '0.0'},
 'semolina': {'carbs': '72.8',
              'fats': '1.05',
              'fiber': '3.9',
              'protein': '12.7'},
 'tomato': {'carbs': '3.6', 'fats': '0.2', 'fiber': '1.7', 'protein': '0.9'},
 'turmeric': {'carbs': '69.4',
              'fats': '5.1',
              'fiber': '20.0',
              'protein': '6.3'},
 'turmeric ground': {'carbs': '64.9',
                     'fats': '9.9',
                     'fiber': '21.1',
                     'protein': '7.8'},
 'water': {'carbs': '0.0', 'fats': '0.0', 'fiber': '0.0', 'protein': '0.0'},
 'wheat': {'carbs': '71.2', 'fats': '1.5', 'fiber': '12.5', 'protein': '11.8'},
 'wheat flour': {'carbs': '73.9',
                 'fats': '0.9',
                 'fiber': '2.7',
                 'protein': '11.0'}}

